version: "3.8"
services:
  db:
    container_name: postgresql-basic-laravel-user-api
    image: postgres:15.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/docker-database/postgresql-basic-laravel-user-api/data:/var/lib/postgresql/data
volumes:
    db:
        driver: local
